"""
Django settings for AgricultureTrip project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x0109zy#i#2mpw75x)j4lbq3i-#x4tzz_dx=6i**qe8@lo@gt8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [

    'simpleui',  # 美化后台界面
    'corsheaders',  # 跨域配置
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # DRF组件
    'trip',  # 旅游app
    'drf_yasg',  # 接口文档
    'django_filters',  # 过滤器
    'django_extensions',  # python manage.py graph_models -a -o myapp_models.png Django拓展,用于生成数据库关系图
    'django_crontab',  # 定时任务

]
CRONJOBS = [
    ('0 0 * * *', 'Trip.cron.cron'),  # 每天0点执行定时任务
    ('0 0 * * *', 'Trip.cron.update_record_info'),  # 每天0点给拥有作物创建一条记录
    ('0 0 * * *', 'Trip.cron.create_record'),  # 每天每10秒调用一次接口用来更新当天记录的基本信息
]
# 支持跨域配置开始
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
REST_FRAMEWORK = {
    # 分页器
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': '8',
    # 异常处理
    'EXCEPTION_HANDLER': 'trip.utils.custom_exception',
    # 过滤器
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend',
                                'rest_framework.filters.OrderingFilter', ]
}
CSRF_TRUSTED_ORIGINS = [
    'http://82.157.194.239:8083',
]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 后端跨域
    'django.middleware.gzip.GZipMiddleware',  # 配置压缩中间件
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AgricultureTrip.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AgricultureTrip.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# 数据库配置
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'AgricultureTrip',  # 数据库名称
        'USER': 'root',  # 账号
        'PASSWORD': '123',  # 密码
        'HOST': '172.17.0.1', #
        'PORT': '8082',
        'OPTIONS': {
            "init_command": "SET foreign_key_checks = 0;",
        }
    }
}
# 数据库配置
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'AgricultureTrip',  # 数据库名称
#         'USER': 'root',  # 账号
#         'PASSWORD': '',  # 密码
#         'HOST': 'localhost', #
#         'PORT': '3306',
#         'OPTIONS': {
#             "init_command": "SET foreign_key_checks = 0;",
#         }
#     }
# }
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
# 去掉默认Logo或换成自己Logo链接
SIMPLEUI_LOGO = '/upload/avatar/fd35784b918607936b7af47ed2d9ba2e_1.jpg'
# 更改默认语言为中文
LANGUAGE_CODE = 'zh-hans'

# 更改时区为上海
TIME_ZONE = 'Asia/Shanghai'
USE_TZ = False

# 日期时间格式
DATE_FORMAT = 'Y-m-d'
DATETIME_FORMAT = 'Y-m-d H:i:s'

# 上传文件路径
# 并在urls.py配置+static
# 媒体文件配置
# 媒体文件配置
MEDIA_URL = '/upload/'  # 访问媒体文件的URL前缀
MEDIA_ROOT = os.path.join(BASE_DIR, 'upload')  # 媒体文件存储目录

# 静态文件 (CSS, JavaScript, Images)
# STATIC_URL = '/static/'
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # 'static'可以根据你的偏好更改
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),  # 指定开发环境中静态文件的目录
# ]
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS_ORIGIN_ALLOW_ALL = True
# CORS_ALLOW_CREDENTIALS = True
# CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOW_HEADERS = (
#     "Access-Token",
#     "Authorization",
#     "*",)
# CORS_ALLOW_METHODS = ('DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT', 'VIEW',)
